INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12110','Consultation - in office: (age 0-1)',80.12);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00110','Consultation - in office: (age 2 - 49)',72.82);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15310','Consultation – in office (age 50 - 59)',80.12);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16110','Consultation - in office: (age 60 - 69)',83.77);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17110','Consultation - in office: (age 70 - 79)',94.67);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18110','Consultation - in office: (age 80+)',109.23);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00116','Special in-hospital consultation',154.33);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12210','Consultation – out of office (age 0 – 1)',96.15);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13210','Consultation – out of office (age 2 - 49)',87.39);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15210','Consultation – out of office (age 50 - 59)',96.15);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16210','Consultation – out of office (age 60 - 69)',100.51);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17210','Consultation – out of office (age 70 - 79)',113.62);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18210','Consultation – out of office (age 80+)',131.09);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12101','Complete examination - in office (age 0-1)',72.83);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00101','Complete examination - in office (age 2-49)',66.20);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15301','Complete examination – in office (age 50 – 59)',72.83);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16101','Complete examination - in office (age 60-69)',76.15);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17101','Complete examination - in office (age 70-79)',86.07);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18101','Complete examination - in office (age 80+)',99.29);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12201','Complete examination - out of office (age 0-1)',87.40);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13201','Complete examination - out of office (age 2-49)',79.45);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15201','Complete examination - out of office (age 50-59)',87.40);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16201','Complete examination - out of office (age 60-69)',91.38);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17201','Complete examination - out of office (age 70-79)',103.27);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18201','Complete examination - out of office (age 80+)',119.16);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12100','Visit - in office (age 0-1)',32.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00100','Visit - in office (age 2-49)',29.79);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15300','Visit – in office (age 50-59)',32.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16100','Visit - in office (age 60-69)',34.23);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17100','Visit - in office (age 70-79)',38.70);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18100','Visit - in office (age 80+)',44.67);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13070','In office assessment of an unrelated condition(s) in association with a WorkSafe BC service',15.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13075','In office assessment of an unrelated condition(s) in association with an ICBC service',15.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12200','Visit - out of office (age 0-1)',39.32);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13200','Visit - out of office (age 2-49)',35.73);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15200','Visit – out of office (age 50-59)',39.32);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16200','Visit - out of office (age 60-69)',41.08);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17200','Visit - out of office (age 70-79)',46.45);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18200','Visit - out of office (age 80+)',53.60);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13763','Three patients',24.65);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13764','Four patients',19.92);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13765','Five patient',17.11);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13766','Six patients',15.23);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13767','Seven patients',13.89);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13768','Eight patients',12.88);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13769','Nine patients',12.09);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13770','Ten patients',11.45);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13771','Eleven patients',10.03);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13772','Twelve patients',9.43);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13773','Thirteen patients',8.74);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13774','Fourteen patients',8.58);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13775','Fifteen patients',8.23);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13776','Sixteen patients',7.98);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13777','Seventeen patients',7.65);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13778','Eighteen patients',7.48);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13779','Nineteen patients',7.22);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13780','Twenty patients',7.05);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13781','Greater than 20 patients (per patient)',6.79);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12120','Individual counselling - in office (age 0-1)',57.03);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00120','Individual counselling - in office (age 2-49)',51.84);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15320','Individual counselling – in office (age 50-59)',57.03);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16120','Individual counselling - in office (age 60-69)',59.62);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17120','Individual counselling - in office (age 70-79)',67.40);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18120','Individual counselling - in office (age 80+)',77.77);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('12220','Individual counselling - out of office (age 0-1)',68.43);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13220','Individual counselling - out of office (age 2-49)',62.20);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15220','Individual counselling – out of office (age 50 – 59)',68.43);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('16220','Individual counselling - out of office (age 60-69)',71.55);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('17220','Individual counselling - out of office (age 70-79)',80.85);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('18220','Individual counselling - out of office (age 80+)',93.30);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00121','- first full hour',84.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00122','- second hour, per 1/2 hour or major portion thereof',42.41);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13036','Telehealth GP in-office Consultation',80.37);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13037','Telehealth GP in-office Visit',33.56);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13041','- First full hour',84.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13042','- Second hour, per ½ hour or major portion thereof',42.41);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13016','Telehealth GP out-of-office Consultation',105.65);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13017','Telehealth GP out-of-office Visit',40.31);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13021','- First full hour',84.75);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13022','- Second hour, per ½ hour or major portion thereof',42.41);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13015','HIV/AIDS Primary Care Management – in or out of office - per half hour or major portion thereof',82.30);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00109','Acute care hospital admission visit',79.10);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00108','Hospital visit',31.31);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00128','Supportive care hospital visit',26.51);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00127','Terminal care facility visit',40.27);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13338','Community based GP, first facility visit of the day bonus, extra (active hospital privileges) (for routine, supportive or terminal care)',35.53);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13008','Community based GP: hospital visit (active hospital privileges)',40.27);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13028','Community based GP: supportive care hospital visit (active hospital privileges)',34.09);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13339','Community based GP, first facility visit of the day bonus, extra, (courtesy/associate privileges)',28.25);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13228','Community based GP: hospital visit (courtesy/associate privileges)',28.25);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00113','Evening (between 1800 hours and 2300 hours)',48.73);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00105','Night (between 2300 hours and 0800 hours)',68.55);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00123','Saturday, Sunday or Statutory Holiday',48.73);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00114','One or multiple patients, per patient',32.22);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P13334','Community based GP, long term care facility visit - first visit of the day bonus, extra',32.22);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00115','Nursing home visit – one patient, when specially called and patient seen between hours of 0800 hrs and 2300 hrs – any day',108.95);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00112','Emergency visit (call placed between hours of 0800 and 1800 hours) – weekdays',108.95);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00111','An emergency home (or scene of accident) visit for an acutely ill or injured patient immediately followed by a trip to hospital to arrange for emergency admission and to include immediate associated hospital visit',110.92);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13000','Telephone advice to a Community Health Representative in First Nation’s Communities',14.88);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13005','Advice about a patient in Community Care',14.88);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('14090','Prenatal visit - complete examination',79.46);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('14091','- subsequent examination',29.79);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P14094','Post-natal office visit',29.79);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('14104','Delivery and post-natal care (1-14 days in-hospital)',550.55);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('14108','Post-natal care after elective caesarean section(1-14 days in-hospital)',113.26);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('14109','Primary management of labour and attendance at delivery and post-natal care associated with emergency caesarean section (1-14 days in-hospital)',458.58);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('T14545','Medical abortion',155.31);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15120','Pregnancy test, immunologic - urine',10.94);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00118','Attendance at caesarian section (if specifically requested by surgeon for care of baby only)',85.50);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00119','Routine care of newborn in hospital',87.40);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('14540','Insertion of intrauterine contraceptive device (operation only) 40.61',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('Y13655','GP vasectomy bonus associated with bilateral vasectomy',20.20);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13194','First Surgical Assist of the Day',75.76);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00195','- less than $317.00 inclusive',130.08);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00196','- $317.01 to 529.00 inclusive',183.39);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00197','- over $529.01',240.16);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00198','Time, after 3 hours of continuous surgical assistance for one patient, each 15 minutes or fraction thereof',27.47);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00193','Non-CVT-certified surgical assistance at open-heart surgery, per quarter hour or major portion thereof',27.78);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13052','Anesthetic evaluation - non-certified anesthesiologist',38.71);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00190','Forms of treatment other than excision, X-ray, or Grenz ray; such as removal of haemangiomas and warts with electrosurgery, cryotherapy, etc.- per visit (operation only)',29.46);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13660','Metatarsal bone - closed reduction (operation only) 49.69',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13600','Biopsy of skin or mucosa (operation only) 48.88',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13601','Biopsy of facial area (operation only) 48.88',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13605','Opening superficial abscess, including furuncle - operation only 41.87',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13611','Minor laceration or foreign body - requiring anesthesia - operation only 62.46',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13612','Extensive laceration greater than 5 cm (maximum charge 35 cm) - operation only - per cm 12.52',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13620','Excision of tumour of skin or subcutaneous tissue or small scar under local anesthetic - up to 5 cm (operation only) 62.46',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13621','- additional lesions removed at the same sitting (maximum per sitting, five) each (operation only)',31.24);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13622','Localized carcinoma of skin proven histopathologically (operation only) 69.00',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13630','Paronychia - operation only (operation only) 33.46',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13631','Removal of nail - simple operation only 33.46',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13632','- with destruction of nail bed (operation only) 67.69',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('13633','Wedge excision of one nail (operation only) 59.72',2);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('Y10710','In office Anoscopy',7.45);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00012','Venepuncture and dispatch of specimen to laboratory, when no other blood work performed',5.62);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15132','Candida Culture',6.50);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P15134','Examination for pinworm ova',5.76);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15136','Fungus, direct examination, KOH preparation',8.23);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15100','Glucose - semiquantitative (dipstick analysed visually or by reflectance meter)',3.53);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15137','Hemoglobin cyanmethemoglobin method and/or haematocrit.',3.07);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15000','Hemoglobin - other methods',1.55);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15110','Occult blood – feces',5.12);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15120','Pregnancy test, immunologic - urine',10.94);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('30015','Secretion smear for eosinophils',7.15);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15138','Sedimentation rate',2.46);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15139','Sperm, Seminal examination for presence or absence',14.40);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P15140','Stained smear',7.25);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('P15141','Trichomonas and/or Candida direct examination',5.49);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15130','Urinalysis - Chemical or any part of (screening)',2.05);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15131','Urinalysis - Microscopic examination of centrifuged deposit',4.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15142','Urinalysis - Complete diagnostic, semi-quant and micro',5.37);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('15143','White cell count only (see hematology protocol)',6.31);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('00117','Interpretation of electrocardiogram by non-internist',9.77);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14015','General Practice Facility Patient Conference: when requested by a facility to review ongoing management of the patient in that facility or to determine whether a patient in a facility with complex supportive care needs can safely return to the community or transition to a supportive care or long-term facility - per 15 minutes or greater portion thereof',40.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14018','General Practice Urgent Telephone Conference with a Specialist Fee: Conferencing on an urgent basis (within 2 hours of request for a telephone conference) with a specialist or GP with specialty training by telephone followed by the creation, documentation, and implementation of a clinical action plan for the care of patients with acute needs; i.e. requiring attention within the next 24 hours and communication of that plan to the patient or patient''s representative',40.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14079','GP Telephone/Email Management Fee',15.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14033','GP Annual Complex Care Management Fee',315.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14066','Personal Health Risk Assessment',50.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14010','Maternity Care Network Initiative Payment',2100.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14004','Incentive for Full Service General Practitioner - Obstetric Delivery bonus associated with vaginal delivery and postnatal care',275.28);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14005','Incentive for Full Service General Practitioner - Obstetric delivery bonus associated with management of labour and transfer to a higher level of care facility for delivery',114.64);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14009','Incentive for Full Service General Practitioner - Obstetric Delivery bonus related to attendance at delivery and postnatal care associated with emergency caesarean section',229.29);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14008','Incentive for Full Service General Practitioner – Obstetric Delivery bonus associated with postnatal care after an elective C-section',56.63);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14043','GP Mental Health Planning Fee',100.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14044','GP Mental Health Management Fee age 2 – 49',51.84);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14045','GP Mental Health Management Fee age 50 - 59',57.03);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14046','GP Mental Health Management Fee age 60 - 69',59.62);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14047','GP Mental Health Management Fee age 70 - 79',67.40);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14048','GP Mental Health Management Fee age 80+',77.77);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14063','Palliative Care planning fee',100.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14021','GP with Specialty Training Telephone Advice - Initiated by a Specialist or General Practitioner, Response within 2 hours',60.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14022','GP with Specialty Training Telephone Patient Management - Initiated by a Specialist or General Practitioner, Response in One Week',40.00);
INSERT INTO Encounter (e_id, e_type, e_price) VALUES ('G14023','GP with Specialty Training Telephone Patient Management / Follow-Up',20.00);
